apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysql-exporter
  name: mysql-exporter
spec:
  ports:
    - name: "9104"
      port: 9104
      targetPort: 9104
  selector:
    io.kompose.service: mysql-exporter
