apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres-exporter
  name: postgres-exporter
spec:
  ports:
    - name: "9188"
      port: 9188
      targetPort: 9187
  selector:
    io.kompose.service: postgres-exporter
