default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 192.168.0.102
      user: root
      password: root@@123
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
