apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: airflow-apiserver
  name: airflow-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-apiserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: airflow-apiserver
    spec:
      containers:
        - args:
            - api-server
          image: dambyul/airflow:de-template
          name: airflow-apiserver
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: airflow
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8080/api/v2/version
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
      restartPolicy: Always