apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: airflow-scheduler
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: airflow-scheduler
    spec:
      containers:
        - name: airflow-scheduler
          image: dambyul/airflow:de-template
          args:
            - scheduler
          envFrom:
            - configMapRef:
                name: airflow
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8974/health
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
      restartPolicy: Always