apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: airflow-apiserver
  name: airflow-apiserver
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    io.kompose.service: airflow-apiserver