apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: airflow-triggerer
  name: airflow-triggerer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airflow-triggerer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: airflow-triggerer
    spec:
      containers:
        - name: airflow-triggerer
          image: dambyul/airflow:de-template
          args:
            - triggerer
          envFrom:
            - configMapRef:
                name: airflow
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  airflow jobs check --job-type TriggererJob --hostname $(hostname) || exit 0
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
      restartPolicy: Always
