apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: airflow-postgres-exporter
  name: airflow-postgres-exporter
spec:
  ports:
    - name: "9187"
      port: 9187
      targetPort: 9187
  selector:
    io.kompose.service: airflow-postgres-exporter
