apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: statsd-exporter
  name: statsd-exporter
spec:
  ports:
    - name: "9102"
      port: 9102
      targetPort: 9102
  selector:
    io.kompose.service: statsd-exporter
