apiVersion: batch/v1
kind: Job
metadata:
  name: dbt-git-sync
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: dbt-git-sync
          image: alpine/git
          command:
            - sh
            - -c
            - |
              rm -rf /dbt/* && \
              git clone --depth=1 --filter=blob:none --sparse https://github.com/dambyul/DE-Template.git /tmp/repo && \
              cd /tmp/repo && \
              git sparse-checkout set dbt && \
              cp -r dbt/* /dbt/
          volumeMounts:
            - name: dbt-data
              mountPath: /dbt
      volumes:
        - name: dbt-data
          persistentVolumeClaim:
            claimName: dbt-data