apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    # Edit the jobs for use
    scrape_configs:
      - job_name: 'airflow'
        static_configs:
          - targets: ['statsd-exporter:9102']

      - job_name: 'airflow-postgres'
        static_configs:
          - targets: ['airflow-postgres-exporter:9187']

      - job_name: 'mysql'
        static_configs:
          - targets: ['mysql-exporter:9104']

      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm
