global:
  scrape_interval: 15s

# Edit the jobs for use
scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['192.168.0.102:9125']

  - job_name: 'airflow-postgres'
    static_configs:
      - targets: ['192.168.0.102:9187']

  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.0.102:9104']

  - job_name: 'postgres'
    static_configs:
      - targets: ['192.168.0.102:9188']
