apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-apiserver
  namespace: {{ .Values.namespace }}
  labels:
    app: airflow-apiserver
spec:
  replicas: {{ .Values.replicaCount.apiserver }}
  selector:
    matchLabels:
      app: airflow-apiserver
  template:
    metadata:
      labels:
        app: airflow-apiserver
    spec:
      containers:
      - name: apiserver
        image: {{ .Values.image.airflow }}
        args: ["api-server"]
        ports:
        - containerPort: 8080
        resources:
{{ toYaml .Values.resources.apiserver | indent 10 }}
        envFrom:
          - configMapRef:
              name: {{ .Values.envFrom.configMapRefName | default "airflow-common" }}
          - secretRef:
              name: {{ .Values.envFrom.secretRefName | default "airflow-secrets" }}
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc