apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFrom.secretRefName | default "airflow-secrets" }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  # Postgres 기본 정보
  POSTGRES_USER: {{ .Values.secrets.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgres.db | quote }}

  # Airflow DB/브로커 연결
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: {{ .Values.secrets.airflow.sql_alchemy_conn | quote }}
  AIRFLOW__CELERY__RESULT_BACKEND: {{ .Values.secrets.airflow.celery_result_backend | quote }}
  AIRFLOW__CELERY__BROKER_URL: {{ .Values.secrets.airflow.broker_url | quote }}

  # Airflow Admin 사용자
  AIRFLOW_ADMIN_USERNAME: {{ .Values.secrets.airflow.admin.username | quote }}
  AIRFLOW_ADMIN_PASSWORD: {{ .Values.secrets.airflow.admin.password | quote }}
  AIRFLOW_ADMIN_FIRSTNAME: {{ .Values.secrets.airflow.admin.firstname | quote }}
  AIRFLOW_ADMIN_LASTNAME: {{ .Values.secrets.airflow.admin.lastname | quote }}
  AIRFLOW_ADMIN_EMAIL: {{ .Values.secrets.airflow.admin.email | quote }}

  # Airflow 보안 키
  AIRFLOW__CORE__FERNET_KEY: {{ .Values.secrets.airflow.fernet_key | quote }}
  AIRFLOW__API_AUTH__JWT_SECRET: {{ .Values.secrets.airflow.jwt_secret | quote }}

  # 원격 로그 설정
  AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
  AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: {{ .Values.secrets.airflow.remote_log_folder | quote }}
  AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: {{ .Values.secrets.airflow.remote_log_conn_id | quote }}

  # Airflow Connections
  AIRFLOW_CONN_MYSQL_DW: {{ .Values.secrets.connections.MYSQL_DW | quote }}
  AIRFLOW_CONN_S3_LOG: {{ .Values.secrets.connections.S3_LOG | quote }}