{{- $ns := .Values.namespace -}}
{{- with .Values.exporters.postgres -}}
{{- range .instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter-{{ .name }}
  namespace: {{ $ns }}
spec:
  replicas: {{ $.Values.exporters.postgres.replicas }}
  selector:
    matchLabels:
      app: postgres-exporter-{{ .name }}
  template:
    metadata:
      labels:
        app: postgres-exporter-{{ .name }}
    spec:
      containers:
        - name: postgres-exporter
          image: {{ $.Values.exporters.postgres.image }}
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://{{ .user }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}?sslmode={{ .sslmode }}"
{{- if .env }}
{{ toYaml .env | nindent 12 }}
{{- end }}
          ports:
            - containerPort: {{ $.Values.exporters.postgres.port }}
          resources:
{{ toYaml $.Values.exporters.postgres.resources | nindent 12 }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-{{ .name }}
  namespace: {{ $ns }}
{{- with $.Values.exporters.postgres.service.labels }}
  labels:
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with $.Values.exporters.postgres.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ $.Values.exporters.postgres.service.type }}
  selector:
    app: postgres-exporter-{{ .name }}
  ports:
    - name: http
      port: {{ $.Values.exporters.postgres.port }}
      targetPort: {{ $.Values.exporters.postgres.port }}
{{- end }}
{{- end }}
