{{- $ns := .Values.namespace -}}
{{- with .Values.exporters.redis -}}
{{- range .instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter-{{ .name }}
  namespace: {{ $ns }}
spec:
  replicas: {{ $.Values.exporters.redis.replicas }}
  selector:
    matchLabels:
      app: redis-exporter-{{ .name }}
  template:
    metadata:
      labels:
        app: redis-exporter-{{ .name }}
{{- with $.Values.exporters.redis.podLabels }}
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with $.Values.exporters.redis.podAnnotations }}
      annotations:
{{ toYaml . | nindent 8 }}
{{- end }}
    spec:
      containers:
        - name: redis-exporter
          image: {{ $.Values.exporters.redis.image }}
          imagePullPolicy: {{ $.Values.exporters.redis.imagePullPolicy | default "IfNotPresent" }}
          args:
            - "--redis.addr=redis://{{ .host }}:{{ .port }}"
{{- if .user }}
            - "--redis.user={{ .user }}"
{{- end }}
{{- if .password }}
            - "--redis.password=$(REDIS_PASSWORD)"
{{- end }}
{{- if .extraArgs }}
{{- range .extraArgs }}
            - "{{ . }}"
{{- end }}
{{- end }}
{{- if .password }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "redis-auth-%s" .name) .passwordSecretName }}
                  key: {{ default "password" .passwordSecretKey }}
{{- else if $.Values.exporters.redis.env }}
          env:
{{ toYaml $.Values.exporters.redis.env | nindent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ $.Values.exporters.redis.port }}
          readinessProbe:
            httpGet: { path: /metrics, port: http }
          livenessProbe:
            httpGet: { path: /metrics, port: http }
          resources:
{{ toYaml $.Values.exporters.redis.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-{{ .name }}
  namespace: {{ $ns }}
{{- with $.Values.exporters.redis.service.labels }}
  labels:
{{ toYaml . | nindent 4 }}
{{- end }}
{{- with $.Values.exporters.redis.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ $.Values.exporters.redis.service.type }}
  selector:
    app: redis-exporter-{{ .name }}
  ports:
    - name: http
      port: {{ $.Values.exporters.redis.port }}
      targetPort: http
{{- end }}
{{- end }}
