apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: {{ .Values.namespace }}
  labels:
{{ include "chart.mergeLabels" . | indent 4 }}
  annotations:
{{- $ann := include "chart.mergeAnnotations" . -}}
{{- if $ann | trim }}
{{ $ann | indent 4 }}
{{- else }}
    {}
{{- end }}
spec:
  replicas: {{ .Values.redisExporter.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.redisExporter.podLabels }}
{{ toYaml .Values.redisExporter.podLabels | indent 8 }}
{{- end }}
      annotations:
{{- if .Values.redisExporter.podAnnotations }}
{{ toYaml .Values.redisExporter.podAnnotations | indent 8 }}
{{- else }}
        {}
{{- end }}
    spec:
      containers:
        - name: redis-exporter
          image: {{ .Values.redisExporter.image }}
          imagePullPolicy: {{ .Values.redisExporter.imagePullPolicy | default "IfNotPresent" }}
{{- if .Values.redisExporter.env }}
          env:
{{ toYaml .Values.redisExporter.env | indent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.redisExporter.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: {{ .Values.namespace }}
  labels:
{{ include "chart.mergeLabels" . | indent 4 }}
{{- if .Values.redisExporter.service.labels }}
{{ toYaml .Values.redisExporter.service.labels | indent 2 }}
{{- end }}
  annotations:
{{- if .Values.redisExporter.service.annotations }}
{{ toYaml .Values.redisExporter.service.annotations | indent 2 }}
{{- else }}
    {}
{{- end }}
spec:
  type: {{ .Values.redisExporter.service.type }}
  selector:
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.redisExporter.service.port }}
      targetPort: http
