name: Sync dbt to Kubernetes PVC

on:
  push:
    branches: [ main ]

jobs:
  sync-dbt:
    name: Sync dbt to PVC on K8s
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete existing dbt-git-sync Job if present
        run: |
          kubectl delete job dbt-git-sync --ignore-not-found

      - name: Apply dbt-git-sync Job YAML to Kubernetes
        run: |
          kubectl apply -f dbt/k8s/dbt-git-sync.yaml